/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/identity/verify-bvn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify BVN to reach KYC Tier 2 (REQ-ID-020; required by REQ-PAY-004 before any deposit) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        bvn: string;
                    };
                };
            };
            responses: {
                /** @description verified_tier_2 | tier_1_required | bvn_not_verified */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description bvn is not 11 digits. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Both balances (Story 2.2, Betplus_PRD.md §12.3) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description play_balance_kobo, winnings_balance_kobo, currency, registered_source_label. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deposit history (Story 2.6) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of MoneyTransaction-shaped rows with status_history. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/deposits/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fee quote for a deposit — always fee-free, but still confirmed server-side (UX-DR13) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        amount_kobo: number;
                    };
                };
            };
            responses: {
                /** @description quote_id (pass to /wallet/deposits), amount_kobo, fee_kobo (always 0), source_label, destination_label, expected_timing, reversible (always false). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an OPay BankAccount collection (Story 2.3). Requires a verified BVN on file (REQ-PAY-004) — status "bvn_required" means call /identity/verify-bvn first. Endpoint/field names for the underlying OPay call are best-effort (Betplus_PRD.md §12.6 gives the path; no full Collections API doc exists in this repo) — treat as unverified until confirmed against sandbox. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description From /wallet/deposits/quote. */
                        quote_id: string;
                    };
                };
            };
            responses: {
                /** @description status (otp_required | bvn_required | invalid_quote | error), collection_id when otp_required. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/deposits/{id}/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit the OPay OTP to complete a deposit (Story 2.3). Idempotent — replaying after "paid" does not re-credit. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        otp: string;
                    };
                };
            };
            responses: {
                /** @description On "paid", returns the full MoneyTransaction shape; otherwise {status}. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/verify-nin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit date of birth and NIN to reach KYC Tier 1 (Story 1.9, REQ-ID-020..024) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        date_of_birth: string;
                        nin: string;
                    };
                };
            };
            responses: {
                /** @description "under_age" blocks play/deposit immediately — the account is frozen. "nin_not_verified" leaves the player at Tier 0, retryable. "verified_tier_1" upgrades kycTier to 1 (₦200,000/month deposit limit, play permitted). The raw NIN is never in this response, only in the vault (Story 1.10). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "verified_tier_1" | "under_age" | "nin_not_verified";
                        };
                    };
                };
                /** @description Missing or expired access token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description date_of_birth is not a valid past date, or nin is not 11 digits. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start or resume phone registration (Story 1.7, REQ-ID-001..003) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Any accepted Nigerian format; normalised server-side to E.164.
                         * @example 08031234567
                         */
                        msisdn: string;
                    };
                };
            };
            responses: {
                /** @description OTP sent (or already pending). Response is identical whether or not an account already exists for this number (UX-DR17 non-disclosure). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "otp_sent";
                            /** @description Seconds until the OTP expires. */
                            expires_in?: number;
                        };
                    };
                };
                /** @description msisdn is not a valid Nigerian mobile number. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/confirm-identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Look up the OPay-registered name for a verified MSISDN (Story 1.8, REQ-ID-010..013) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        msisdn: string;
                    };
                };
            };
            responses: {
                /** @description Lookup result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "confirm" | "no_wallet" | "error" | "otp_not_verified";
                            /** @description Present only when status is "confirm". Authoritative for payout matching; the client presents it for confirmation but never lets the player edit it (REQ-ID-013). */
                            registered_name?: string;
                        };
                    };
                };
                /** @description msisdn is not a valid Nigerian mobile number. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the player account from a confirmed identity (Story 1.8) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        msisdn: string;
                    };
                };
            };
            responses: {
                /** @description Completion result. On "registered", the player is signed in immediately — access_token/refresh_token/expires_in are present and the same HttpOnly cookies as /auth/sign-in/complete are set (Story 1.11). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "registered" | "identity_not_confirmed" | "already_registered";
                            player_id?: number;
                        } & components["schemas"]["SessionTokens"];
                    };
                };
                /** @description msisdn is not a valid Nigerian mobile number. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a session for an existing account after OTP verification (Story 1.11, REQ-ID-026). Call /auth/register then /auth/register/verify first — this is what "next": "sign_in" in the verify response leads to. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        msisdn: string;
                    };
                };
            };
            responses: {
                /** @description Sign-in result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "signed_in" | "otp_not_verified" | "no_account";
                        } & components["schemas"]["SessionTokens"];
                    };
                };
                /** @description msisdn is not a valid Nigerian mobile number. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token (Story 1.11, REQ-ID-026 — rotation with reuse detection) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Reuse of an already-rotated refresh token revokes its entire token family — every session descended from that sign-in is terminated, not just this one. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "signed_in" | "invalid_token" | "expired" | "reuse_detected";
                        } & components["schemas"]["SessionTokens"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify the OTP sent by /auth/register (Story 1.7) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        msisdn: string;
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Verification result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "verified" | "invalid_or_expired";
                            /**
                             * @description sign_in: an account already exists for this number (only revealed after OTP ownership is proven). identity_confirmation: proceed to Story 1.8. resend: code was wrong/expired or too many attempts were made.
                             * @enum {string}
                             */
                            next?: "sign_in" | "identity_confirmation" | "resend";
                        };
                    };
                };
                /** @description msisdn is not a valid Nigerian mobile number. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Present only when status is "signed_in"/"registered". Also set as HttpOnly, Secure, SameSite=Lax cookies (access_token, refresh_token) for web — these body fields are for non-cookie clients (mobile app, USSD adapter). */
        SessionTokens: {
            access_token?: string;
            refresh_token?: string;
            /** @description Access token TTL in seconds (REQ-ID-026 — 30 minutes). */
            expires_in?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
